# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Future Imperfect Dark"
license = "GNU GPLv3"
licenselink = "https://gitlab.com/initmanfs/hugo-future-imperfect-dark/blob/master/LICENSE.md"
description = "Ported theme of HTML5 UP, future imperfect, with some extra goodies"
homepage = "https://gitlab.com/initmanfs/hugo-future-imperfect-dark"
tags = ["blog", "responsive", "font awesome", "highlight.js", "fancybox 3", "staticman", "netlify"]
features = ["html5", "css3", "responsive"]
min_version = 0.15

[author]
  name = "Initmanfs Team"
  homepage = "https://initmanfs.eu"

# If porting an existing theme
[original]
  name = "Hugo Future Imperfect"
  homepage = "https://github.com/jpescador/hugo-future-imperfect"
  repo = "https://github.com/jpescador/hugo-future-imperfect.git"
