baseurl = "http://hugo.spf13.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Hugo Future Imperfect Dark"
theme = "hugo-future-imperfect-dark"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = "shortname"
googleAnalytics = ""
pluralizeListTitles = false

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Future Imperfect Dark"
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"

# Optional Params
    # RSS icon that appear on the sidebar, next to the social media buttons
    rssAppearAtTop       = true
    rssAppearAtBottom    = true
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Disable showing the social sharing links on blog posts
    socialShareDisabled = false

    # Load custom CSS or JavaScript files. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    customCSS            = ["default"]
    customJS             = ["default"]

    # Enable git informations on posts and pages footer
    enableGitInfo        = true
    gitrepo              = "https://gitlab.com/example/exampleWebSite"

# Disqus will take priority over staticman due to its ease of use. Feel free to check out both and decide.
[params.staticman]
    staticman = false
    username  = ""
    repo      = ""
    branch    = ""

[params.piwik]
    enabled = true
    # URL to the root of the piwik installation.
    # Can include paths after the TLD (e.g https://example.com/piwik/)
    host = "https://piwik.example.com/"
    # ID number of this site. Defaults to 1 if not included
    site_id = 2
    # Include <noscript> tags to track users with javascript disabled
    track_nojs = true
    # Include a link in the site footer to allow users to opt out of analytics
    enable_optout = true


# Enable or disable specifics share buttons
[params.share]
    twitter     = true
    google      = true
    facebook    = true
    reddit      = true
    linkedin    = true
    stumbleupon = true
    email       = true

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Hugo Future Imperfect Dark"

    paragraph = "Another fine responsive site template by <a href=\"http://html5up.net\">HTML5 UP</a>. Ported by Julio Pescador with some extra goodies <i class='fa fa-hand-peace-o'></i>"

    about     = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.pic]
    src       = "/img/main/logo.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    # valid values: circle, imperfect or empty
    type = "imperfect"
    width     = ""

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Languages configurations
[languages]

[languages.en]
    languageName = "English"
    weight       = 2
    title        = "Future Imperfect Dark"
    # Sets the meta tag description, usually reserved for the main page
    description  = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador and Initmanfs team. Powered by Hugo"
    # This will appear on the top left of the navigation bar
    navbarTitle  = "Future Imperfect Dark"

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[languages.en.intro]
    header    = "Hugo Future Imperfect Dark"
    paragraph = "Another fine responsive site template by <a href=\"http://html5up.net\">HTML5 UP</a>. Ported by Julio Pescador and Initmanfs team with some extra goodies <i class='fa fa-hand-peace-o'></i>"
[languages.en.intro.about]
    text     = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."
    url      = "/about/"

[languages.fr]
    languageName = "Français"
    weight       = 1
    title        = "Future Imperfect Sombre"
    # Sets the meta tag description, usually reserved for the main page
    description  = "Le thème de HTML5 UP, Future Imperfect avec quelques petites améliorations, adapté par Julio Pescador et l'équipe de Initmanfs. Généré par Hugo"
    # This will appear on the top left of the navigation bar
    navbarTitle  = "Future Imperfect Sombre"


# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[languages.fr.intro]
    header    = "Hugo Future Imperfect Sombre"
    paragraph = "Un autre thème de site responsive par <a href=\"http://html5up.net\">HTML5 UP</a>. Adapté par Julio Pescador et l'équipe de Initmanfs avec quelques améliorations <i class='fa fa-hand-peace-o'></i>"
[languages.fr.intro.about]
    text     = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."
    url      = "/a-propos/"



# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text

[[languages.en.menu.main]]
    name = "Home"
    url = "/"
    identifier = "fa fa-home"
    weight = 1

[[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    identifier = "fa fa-id-card-o"
    weight = 2

[[languages.en.menu.main]]
    name = "Blog"
    url = "/blog/"
    identifier = "fa fa-newspaper-o"
    weight = 3

[[languages.en.menu.main]]
    name = "Categories"
    url = "/categories/"
    identifier = "fa fa-sitemap"
    weight = 5

[[languages.en.menu.main]]
    name = "Contact"
    url = "/contact/"
    identifier = "fa fa-envelope-o"
    weight = 6

[[languages.fr.menu.main]]
    name = "Accueil"
    url = "/"
    identifier = "fa fa-home"
    weight = 1

[[languages.fr.menu.main]]
    name = "À Propos"
    url = "/a-propos/"
    identifier = "fa fa-id-card-o"
    weight = 2

[[languages.fr.menu.main]]
    name = "Blog"
    url = "/blog/"
    identifier = "fa fa-newspaper-o"
    weight = 3

[[languages.fr.menu.main]]
    name = "Catégories"
    url = "/categories/"
    identifier = "fa fa-sitemap"
    weight = 4

[[languages.fr.menu.main]]
    name = "Contact"
    url = "/contact/"
    identifier = "fa fa-envelope-o"
    weight = 5

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "jpescador"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "julio_pescador"
    email           = ""
[taxonomies]
  category = "categories"
